# HOSPITAL MANAGEMENT DATA CLEANING

In [1]:
# Import libraries
 
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

In [2]:
# Load dataset


df = pd.read_csv(r"d:\my multiple projects\end to end hospital managment project\hospital_management_dataset.csv")

In [3]:
# Verify that load the dataset

df.head()

,appointment_id,appointment_date,appointment_time,appointment_status,check_in_time,consultation_start_time,consultation_end_time,wait_time,spent_time,patient_id,...,admission_date,discharge_date,doctor_fee,medicine_cost,test_cost,room_charges,total_bill,payment_status,payment_method,payment_date
0,A0000001,2025-10-07,10:30:00,Cancelled,10:43:00,11:03:00,11:30:00,20,27,P085180,...,NaN,NaN,5152,2894,2587,0,10633,Paid,Online,2025-10-12
1,A0000002,2025-04-12,09:15:00,Pending,09:32:00,09:39:00,10:13:00,7,34,P028170,...,NaN,NaN,6130,4146,4636,0,14912,Unpaid,NaN,NaN
2,A0000003,2024-02-25,09:30:00,Completed,09:42:00,09:57:00,10:21:00,15,24,P064138,...,NaN,NaN,6524,6497,12064,0,25085,Unpaid,NaN,NaN
3,A0000004,2025-11-27,10:15:00,Pending,10:25:00,10:55:00,11:14:00,30,19,P032004,...,NaN,NaN,728,6087,12042,0,18857,Paid,Insurance,2025-12-02
4,A0000005,2023-08-22,14:30:00,Completed,14:40:00,14:56:00,15:35:00,16,39,P076787,...,2023-08-23,2023-08-30,3295,12600,10050,41485,67430,Unpaid,NaN,NaN

In [4]:
# Quikly understand the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 37 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   appointment_id           500000 non-null  object
 1   appointment_date         500000 non-null  object
 2   appointment_time         500000 non-null  object
 3   appointment_status       500000 non-null  object
 4   check_in_time            500000 non-null  object
 5   consultation_start_time  500000 non-null  object
 6   consultation_end_time    500000 non-null  object
 7   wait_time                500000 non-null  int64
 8   spent_time               500000 non-null  int64
 9   patient_id               500000 non-null  object
 10  patient_name             500000 non-null  object
 11  gender                   500000 non-null  object
 12  age                      500000 non-null  int64
 13  phone_no                 449590 non-null  float64
 14  city                     449893 non-null  object
 15  blood_group              500000 non-null  object
 16  patient_type             500000 non-null  object
 17  doctor_id                500000 non-null  object
 18  doctor_name              500000 non-null  object
 19  department               500000 non-null  object
 20  experience_year          500000 non-null  int64
 21  disease                  500000 non-null  object
 22  severity_level           500000 non-null  object
 23  treatment                500000 non-null  object
 24  medicine                 449918 non-null  object
 25  lab_test                 449639 non-null  object
 26  admission_status         500000 non-null  object
 27  admission_date           249939 non-null  object
 28  discharge_date           249939 non-null  object
 29  doctor_fee               500000 non-null  int64
 30  medicine_cost            500000 non-null  int64
 31  test_cost                500000 non-null  int64
 32  room_charges             500000 non-null  int64
 33  total_bill               500000 non-null  int64
 34  payment_status           500000 non-null  object
 35  payment_method           249914 non-null  object
 36  payment_date             249914 non-null  object
dtypes: float64(1), int64(9), object(27)
memory usage: 141.1+ MB

In [5]:
# Apply descriptive statistics

df.describe()

,wait_time,spent_time,age,phone_no,experience_year,doctor_fee,medicine_cost,test_cost,room_charges,total_bill
count,500000.000000,500000.000000,500000.000000,4.495900e+05,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000
mean,22.480330,32.533540,45.638942,3.549479e+09,18.017340,5247.915198,7503.858354,9998.160036,12984.121902,35734.055490
std,10.389876,16.167002,25.965155,2.595949e+08,10.069499,2739.892989,4331.300276,5775.330178,16265.645685,17999.749142
min,5.000000,5.000000,1.000000,3.100024e+09,1.000000,500.000000,0.000000,0.000000,0.000000,746.000000
25%,13.000000,19.000000,23.000000,3.324390e+09,9.000000,2876.000000,3751.000000,5007.000000,0.000000,21913.000000
50%,22.000000,33.000000,46.000000,3.548402e+09,19.000000,5244.000000,7504.000000,9990.000000,0.000000,31095.000000
75%,31.000000,47.000000,68.000000,3.774306e+09,27.000000,7622.000000,11265.000000,15009.000000,25958.250000,48693.000000
max,40.000000,60.000000,90.000000,3.999993e+09,35.000000,10000.000000,15000.000000,20000.000000,50000.000000,93711.000000

In [6]:
# Standarize column names

df.columns = df.columns.str.strip().str.replace(" ","_").str.lower()

# Verify that standarize the column names

df.columns

Index(['appointment_id', 'appointment_date', 'appointment_time',
       'appointment_status', 'check_in_time', 'consultation_start_time',
       'consultation_end_time', 'wait_time', 'spent_time', 'patient_id',
       'patient_name', 'gender', 'age', 'phone_no', 'city', 'blood_group',
       'patient_type', 'doctor_id', 'doctor_name', 'department',
       'experience_year', 'disease', 'severity_level', 'treatment', 'medicine',
       'lab_test', 'admission_status', 'admission_date', 'discharge_date',
       'doctor_fee', 'medicine_cost', 'test_cost', 'room_charges',
       'total_bill', 'payment_status', 'payment_method', 'payment_date'],
      dtype='object')

In [7]:
# Check data types

df.dtypes

appointment_id              object
appointment_date            object
appointment_time            object
appointment_status          object
check_in_time               object
consultation_start_time     object
consultation_end_time       object
wait_time                    int64
spent_time                   int64
patient_id                  object
patient_name                object
gender                      object
age                          int64
phone_no                   float64
city                        object
blood_group                 object
patient_type                object
doctor_id                   object
doctor_name                 object
department                  object
experience_year              int64
disease                     object
severity_level              object
treatment                   object
medicine                    object
lab_test                    object
admission_status            object
admission_date              object
discharge_date              object
doctor_fee                   int64
medicine_cost                int64
test_cost                    int64
room_charges                 int64
total_bill                   int64
payment_status              object
payment_method              object
payment_date                object
dtype: object

STANDARIZE THE COLUMN DATA TYPES

In [8]:
# Convert all date columns to proper datetime format

date_col = ["appointment_date","admission_date","discharge_date","payment_date"]

for col in date_col:
    
    df[col] = pd.to_datetime(df[col],errors="coerce")

# Convert all time columns to proper datetime format

time_col = ["appointment_time","check_in_time","consultation_start_time","consultation_end_time"]

for col in time_col:
    
    df[col] = pd.to_datetime(df[col],format = "%H:%M:%S",errors="coerce")

In [9]:
# Verify the conversion of the date and time columns

df.dtypes

df.head()

,appointment_id,appointment_date,appointment_time,appointment_status,check_in_time,consultation_start_time,consultation_end_time,wait_time,spent_time,patient_id,...,admission_date,discharge_date,doctor_fee,medicine_cost,test_cost,room_charges,total_bill,payment_status,payment_method,payment_date
0,A0000001,2025-10-07,1900-01-01 10:30:00,Cancelled,1900-01-01 10:43:00,1900-01-01 11:03:00,1900-01-01 11:30:00,20,27,P085180,...,NaT,NaT,5152,2894,2587,0,10633,Paid,Online,2025-10-12
1,A0000002,2025-04-12,1900-01-01 09:15:00,Pending,1900-01-01 09:32:00,1900-01-01 09:39:00,1900-01-01 10:13:00,7,34,P028170,...,NaT,NaT,6130,4146,4636,0,14912,Unpaid,NaN,NaT
2,A0000003,2024-02-25,1900-01-01 09:30:00,Completed,1900-01-01 09:42:00,1900-01-01 09:57:00,1900-01-01 10:21:00,15,24,P064138,...,NaT,NaT,6524,6497,12064,0,25085,Unpaid,NaN,NaT
3,A0000004,2025-11-27,1900-01-01 10:15:00,Pending,1900-01-01 10:25:00,1900-01-01 10:55:00,1900-01-01 11:14:00,30,19,P032004,...,NaT,NaT,728,6087,12042,0,18857,Paid,Insurance,2025-12-02
4,A0000005,2023-08-22,1900-01-01 14:30:00,Completed,1900-01-01 14:40:00,1900-01-01 14:56:00,1900-01-01 15:35:00,16,39,P076787,...,2023-08-23,2023-08-30,3295,12600,10050,41485,67430,Unpaid,NaN,NaT

In [10]:
# Convert all float columns to proper float format

float_col = ["doctor_fee","medicine_cost","test_cost","room_charges","total_bill"]

for col in float_col:
    
    df[col] = df[col].astype(float)

In [11]:
# Validate the datatypes

df.dtypes

appointment_id                     object
appointment_date           datetime64[ns]
appointment_time           datetime64[ns]
appointment_status                 object
check_in_time              datetime64[ns]
consultation_start_time    datetime64[ns]
consultation_end_time      datetime64[ns]
wait_time                           int64
spent_time                          int64
patient_id                         object
patient_name                       object
gender                             object
age                                 int64
phone_no                          float64
city                               object
blood_group                        object
patient_type                       object
doctor_id                          object
doctor_name                        object
department                         object
experience_year                     int64
disease                            object
severity_level                     object
treatment                          object
medicine                           object
lab_test                           object
admission_status                   object
admission_date             datetime64[ns]
discharge_date             datetime64[ns]
doctor_fee                        float64
medicine_cost                     float64
test_cost                         float64
room_charges                      float64
total_bill                        float64
payment_status                     object
payment_method                     object
payment_date               datetime64[ns]
dtype: object

Handle missing values

In [12]:
# Detect missing values

df.isnull().sum()

appointment_id                  0
appointment_date                0
appointment_time                0
appointment_status              0
check_in_time                   0
consultation_start_time         0
consultation_end_time           0
wait_time                       0
spent_time                      0
patient_id                      0
patient_name                    0
gender                          0
age                             0
phone_no                    50410
city                        50107
blood_group                     0
patient_type                    0
doctor_id                       0
doctor_name                     0
department                      0
experience_year                 0
disease                         0
severity_level                  0
treatment                       0
medicine                    50082
lab_test                    50361
admission_status                0
admission_date             250061
discharge_date             250061
doctor_fee                      0
medicine_cost                   0
test_cost                       0
room_charges                    0
total_bill                      0
payment_status                  0
payment_method             250086
payment_date               250086
dtype: int64

Fill missing values

In [13]:
# Fill missing phone no

df["phone_no"] = df["phone_no"].fillna("Not Available")

# Fill missing cities

df["city"] = df["city"].fillna("Unknown")

# Fill missing values in medicine column

df["medicine"] = df["medicine"].fillna("No Medicine")

# Fill missing values in the lab test column

df["lab_test"] = df["lab_test"].fillna("No Test")

In [14]:

df["payment_status"].unique()

# Replace missing payment methods for paid patients

df.loc[(df["payment_status"] == 'Paid') & 
        
        (df["payment_method"].isna()), 
        
        "payment_method"] = "UnKnown"

# Replace missing payment methods for Unpaid patients

df.loc[(df["payment_status"] == 'Unpaid') & 
        
        (df["payment_method"].isna()), 
        
        "payment_method"] = "Not Paid"

In [15]:
# Validate missing values after cleaning

df.isnull().sum()

appointment_id                  0
appointment_date                0
appointment_time                0
appointment_status              0
check_in_time                   0
consultation_start_time         0
consultation_end_time           0
wait_time                       0
spent_time                      0
patient_id                      0
patient_name                    0
gender                          0
age                             0
phone_no                        0
city                            0
blood_group                     0
patient_type                    0
doctor_id                       0
doctor_name                     0
department                      0
experience_year                 0
disease                         0
severity_level                  0
treatment                       0
medicine                        0
lab_test                        0
admission_status                0
admission_date             250061
discharge_date             250061
doctor_fee                      0
medicine_cost                   0
test_cost                       0
room_charges                    0
total_bill                      0
payment_status                  0
payment_method                  0
payment_date               250086
dtype: int64

Handle duplicate records

In [16]:
# Detect duplicate records

df.duplicated().sum()

np.int64(0)

In [17]:
# Drop duplicate records

df = df.drop_duplicates()

In [18]:
# Validate duplicate records after droping

df.duplicated().sum()

np.int64(0)

In [19]:
df.head(1)

,appointment_id,appointment_date,appointment_time,appointment_status,check_in_time,consultation_start_time,consultation_end_time,wait_time,spent_time,patient_id,...,admission_date,discharge_date,doctor_fee,medicine_cost,test_cost,room_charges,total_bill,payment_status,payment_method,payment_date
0,A0000001,2025-10-07,1900-01-01 10:30:00,Cancelled,1900-01-01 10:43:00,1900-01-01 11:03:00,1900-01-01 11:30:00,20,27,P085180,...,NaT,NaT,5152.0,2894.0,2587.0,0.0,10633.0,Paid,Online,2025-10-12

Create function for cleaning categorical columns

In [20]:
# Create function to clean whitespace and standardize text case

def clean_column(col):
    
    df[col] = df[col].str.strip().str.title()

In [21]:
# Clean appointment status column

df["appointment_status"].unique()

clean_column("appointment_status")

In [22]:
# Clean gender column

df["gender"].unique()

clean_column("gender")

In [23]:
# Clean payment status column

df["payment_status"].unique()

clean_column("payment_status")

In [24]:
# Clean payment method column

df["payment_method"].unique()

clean_column("payment_method")

Standardize the dataset and remove negative values in bill and age columns

In [25]:
# Remove negetive age and age greater that one hundred twenty

df = df[(df["age"] > 0) & (df["age"] < 120)]

In [26]:
# Remove negetive billing records from the data set

df = df[df["total_bill"] > 0]

In [30]:
df.head()

,appointment_id,appointment_date,appointment_time,appointment_status,check_in_time,consultation_start_time,consultation_end_time,wait_time,spent_time,patient_id,...,admission_date,discharge_date,doctor_fee,medicine_cost,test_cost,room_charges,total_bill,payment_status,payment_method,payment_date
0,A0000001,2025-10-07,1900-01-01 10:30:00,Cancelled,1900-01-01 10:43:00,1900-01-01 11:03:00,1900-01-01 11:30:00,20,27,P085180,...,NaT,NaT,5152.0,2894.0,2587.0,0.0,10633.0,Paid,Online,2025-10-12
1,A0000002,2025-04-12,1900-01-01 09:15:00,Pending,1900-01-01 09:32:00,1900-01-01 09:39:00,1900-01-01 10:13:00,7,34,P028170,...,NaT,NaT,6130.0,4146.0,4636.0,0.0,14912.0,Unpaid,Not Paid,NaT
2,A0000003,2024-02-25,1900-01-01 09:30:00,Completed,1900-01-01 09:42:00,1900-01-01 09:57:00,1900-01-01 10:21:00,15,24,P064138,...,NaT,NaT,6524.0,6497.0,12064.0,0.0,25085.0,Unpaid,Not Paid,NaT
3,A0000004,2025-11-27,1900-01-01 10:15:00,Pending,1900-01-01 10:25:00,1900-01-01 10:55:00,1900-01-01 11:14:00,30,19,P032004,...,NaT,NaT,728.0,6087.0,12042.0,0.0,18857.0,Paid,Insurance,2025-12-02
4,A0000005,2023-08-22,1900-01-01 14:30:00,Completed,1900-01-01 14:40:00,1900-01-01 14:56:00,1900-01-01 15:35:00,16,39,P076787,...,2023-08-23,2023-08-30,3295.0,12600.0,10050.0,41485.0,67430.0,Unpaid,Not Paid,NaT

In [31]:
# Change the directory to load the data set into a specific folder

import os

os.chdir(r"d:\my multiple projects\end to end hospital managment project")

# Load the cleaned datset to a csv file

df.to_csv("hospital_cleaned_dataset.csv", index = False)